language: php

services:
  - mysql

php:
  - '7.2'

before_install:
  - mysql -e 'CREATE DATABASE laravel;'

before_script:
  - composer install
  - cp .env.testing .env
  - php artisan key:generate --env=testing
  - php artisan migrate

script:
  - vendor/bin/phpunit
